name: CI

on:
  pull_request:
    branches:
    - swiftwasm

jobs:
  macos_build:
    timeout-minutes: 0
    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        brew install cmake ninja
        ./utils/update-checkout --clone --scheme wasm
        export sourcedir=$PWD/..
        cd $sourcedir
        wget -O wasi-sdk.tar.gz https://github.com/swiftwasm/wasi-sdk/releases/download/20190421.6/wasi-sdk-3.19gefb17cb478f9.m-linux.tar.gz
        tar xfz wasi-sdk.tar.gz
        mv wasi-sdk-3.19gefb17cb478f9+m/opt/wasi-sdk ./wasi-sdk
        # Link sysroot/usr/include to sysroot/include because Darwin sysroot doesn't 
        # find header files in sysroot/include but sysroot/usr/include
        mkdir wasi-sdk/share/sysroot/usr/
        ln -s ../include wasi-sdk/share/sysroot/usr/include
        wget -O icu.tar.xz "https://github.com/swiftwasm/icu4c-wasi/releases/download/20190421.3/icu4c-wasi.tar.xz"
        tar xf icu.tar.xz
        cd swift
        ./utils/build-script --debug --wasm \
          --skip-build-benchmarks \
          --extra-cmake-options=" \
            -DSWIFT_PRIMARY_VARIANT_SDK:STRING=WASM \
            -DSWIFT_PRIMARY_VARIANT_ARCH:STRING=wasm32 \
            -DSWIFT_OSX_x86_64_ICU_STATICLIB=TRUE \
            -DSWIFT_BUILD_SOURCEKIT=FALSE \
            -DSWIFT_ENABLE_SOURCEKIT_TESTS=FALSE \
          " \
          --stdlib-deployment-targets "wasm-wasm32" \
          --build-stdlib-deployment-targets "wasm-wasm32" \
          --llvm-targets-to-build "X86;WebAssembly" \
          --build-swift-dynamic-sdk-overlay false \
          --build-swift-static-sdk-overlay false \
          --wasm-wasi-sdk "$sourcedir/wasi-sdk" \
          --wasm-icu-uc "$sourcedir/icu_out/lib/libicuuc.a" \
          --wasm-icu-uc-include "$sourcedir/icu_out/include" \
          --wasm-icu-i18n "$sourcedir/icu_out/lib/libicui18n.a" \
          --wasm-icu-i18n-include "$sourcedir/icu_out/include" \
          --wasm-icu-data "todo-icu-data" \
          --build-swift-static-stdlib
