name: CI

on:
  pull_request:
    branches:
    - swiftwasm

jobs:
  macos_build:
    timeout-minutes: 0
    runs-on: macOS-10.14

    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      run: |
        ./utils/build-script --debug --wasm \
          --skip-build-benchmarks \
          --extra-cmake-options=" \
            -DSWIFT_PRIMARY_VARIANT_SDK:STRING=WASM \
            -DSWIFT_PRIMARY_VARIANT_ARCH:STRING=wasm32 \
            -DSWIFT_OSX_x86_64_ICU_STATICLIB=TRUE \
            -DSWIFT_BUILD_SOURCEKIT=FALSE \
            -DSWIFT_ENABLE_SOURCEKIT_TESTS=FALSE \
          " \
          --stdlib-deployment-targets "wasm-wasm32" \
          --build-stdlib-deployment-targets "wasm-wasm32" \
          --llvm-targets-to-build "X86;WebAssembly" \
          --build-swift-dynamic-sdk-overlay false \
          --build-swift-static-sdk-overlay false \
          --wasm-wasi-sdk "$sourcedir/wasi-sdk" \
          --wasm-icu-uc "$sourcedir/icu_out/lib/libicuuc.a" \
          --wasm-icu-uc-include "$sourcedir/icu_out/include" \
          --wasm-icu-i18n "$sourcedir/icu_out/lib/libicui18n.a" \
          --wasm-icu-i18n-include "$sourcedir/icu_out/include" \
          --wasm-icu-data "todo-icu-data" \
          --build-swift-static-stdlib
